#! /bin/bash
# search lshw -short file for needles
# fail if you don't find them

scrape() {
    echo "$out"
    if ! echo "$out" | grep -q "$needle"; then
	echo FAILED, needed "$needle"
	fail=1
    fi
}

lshw_short_file=/tmp/lshw.short
sudo lshw -short > $lshw_short_file

if [[ $? != 0 ]]; then
	echo FAIL - must run on modern Linux, not Ubuntu 5.10
fi

# look for needles in haystack
# if you don't find them, FAIL.

fail=0

# Intel(R) Core(TM) i5-2510E CPU @ 2.50GHz
needle=i5-2510E.CPU...2.5
out=$(grep processor $lshw_short_file | grep "$needle")
scrape

# 4GiB total memory
needle=4GiB.System.Memory
out=$(grep memory $lshw_short_file | grep -v empty | grep "$needle" )
scrape

# / disk
# INTEL SSD
needle=SSDSC2
out=$(grep /dev/sda $lshw_short_file | grep "$needle")
scrape

# /home
# INTEL SSD
needle=SSDSC2
out=$(grep /dev/sdb $lshw_short_file | grep "$needle")
scrape

# check that drives are in SATA 1 and 2, not 3 and 4
needle="0:0:0:0"
out=$(lsscsi | grep /dev/sda | grep "$needle")
scrape
needle="1:0:0:0"
out=$(lsscsi | grep /dev/sdb | grep "$needle")
scrape

# check that /home has been set to the 2nd disk
needle=sdb1
out=$(mount | grep home | grep "$needle")
scrape

if [[ $fail == 1 ]] ; then
	echo FAILED
	exit 1
else
	echo PASSED
	exit 0
fi
