#! /bin/bash

# guidance script for pre-ship software check

# these are escape codes for bold and color.
# note that handling escape codes works differently in different shells.
# this is for /bin/bash.

treset="\e[0m"
tbold="\e[1m"
tred="\e[31m"
tgreen="\e[32m"
tyellow="\e[33m"
tblue="\e[34m"

PERSONALITY=$(cat /opt/imt/personality)

eche () {
    echo -e $*
}

econt () {
    eche
    read -p "ENTER to Continue: "
    eche
    eche "${tbold}########################################${treset}"
    eche
}

if ! cmp -s /opt/imt/robot/imt_config/imt.rc /home/imt/imt_config/imt.rc; then
    eche /home/imt/imt_config/imt.rc is ${tbold}not the standard production version.
    eche Make sure that this is correct.${treset}
    econt
fi

source /opt/imt/robot/lib/imt_base.rc

if ! $CROB_HOME/tools/${PERSONALITY}plc check-ready-lamp; then
    echo "Ready lamp is not on.  Please check stop buttons"
    eche and make sure that both Power and Ready lamps are lit.
    exit 1
fi

eche
eche ${tbold}Production Software Check${treset}
eche
eche This check must be run after production
eche immediately prior to packing for shipment.
eche It may be run at other times.
eche
eche ${tbold}If you make changes to the software system during or after
eche this check, the full check must be run again.${treset}
eche
eche "This script may be interrupted with ^C and run multiple times."
eche "Nothing in this script changes robot files on the system,"
eche "(like calibration files or other robot software)."
eche "If changes are required, you must do that in another window."
eche
eche "This script does change some files that do not affect the"
eche "robot software system state, like emptying the Trash folder."
eche
eche "If you find problems that require a fix, ^C out of this check,"
eche "fix the problem, and run the check again from the beginning."
eche "If you can't solve a problem, get help from software engineering."
eche "Continue until the full check runs cleanly."
econt

eche "Check that computer components are correct."
eche "Should report PASSED."
eche
$CROB_HOME/tools/check_comp
econt

if ! diff /opt/imt/robot/imt_config/ucsettings.rc $IMT_CONFIG/ucsettings.rc; then
eche 
eche ${tbold}ucsettings.ini in $IMT_CONFIG is different from the default.${treset}
eche
eche Make absolutely sure that this is what you want and that
eche you are not overriding something that you should not be.
econt
fi

eche "Check that the fans are properly connected."
eche "If the fans do not do as stated, stop the test."
eche

eche "Fans to OFF."
echo f 0   | nc -q 1 localhost imtuc
read -p "Press enter."

eche "Fans to FULL POWER."
echo f 100 | nc -q 1 localhost imtuc
read -p "Press enter."

eche "Fans to NORMAL power."
echo f -1  | nc -q 1 localhost imtuc
econt

eche Check /opt/imt for current version and to make sure old versions
eche are removed.
eche
echo -n "The installed software version is: "
ls -l /opt/imt | grep -- 'robot.->' | sed 's/.*robot -> //' | sed s/.opt.imt.//

eche
eche ls -l /opt/imt
ls -l /opt/imt
econt

eche Check /home to make sure the only users are imt and recovery:
eche "(lost+found directory entry may also be present.)"
eche
eche ls -l /home
ls -l /home
econt

echo -n "Emptying Trash folder..."
rm -rf $HOME/.Trash/* $HOME/*~ $HOME/Desktop/*~
eche Done.
eche

echo "Turning off incoming ssh..."
sudo sh -c "echo manual > /etc/init/ssh.override"
eche Done
eche '(To turn ssh back on, run: sudo rm /etc/init/ssh.override)'
eche

econt

eche Check $IMT_CONFIG/robots to make sure there are
eche no extra robot configurations there.
eche
eche ls -l $IMT_CONFIG/robots
ls -l $IMT_CONFIG/robots
econt

eche Check relevant data from cal files, that each file has
eche correct data, and that data matches in both files if it should.
eche For all robots, check that calibration file line has a correct
eche serial number and customer name \(not just a country/city name\).
eche make sure there are no lines that say \"nnn customer\"
eche where there should be a customer name.
eche
eche For arm robots, check that torque_xforms and torque_offsets are set
eche and that have_ft is set correctly.
eche
(
cd $IMT_CONFIG/robots
grep -E "^s.have.ft|^..Calib|^..Date|^..Last|que.xform|que.offset|nnn|customer" */imt2.cal
)
econt

eche Check cal files to make sure they have correct customer
eche annotations, ft_cal customizations, and other custom settings.
eche This step runs tkdiff on the planar and planarhand files, and
eche firefox on the wrist file.  You must close these windows to proceed.
eche 

# a planar/hand
if [[    -e $IMT_CONFIG/robots/planar/imt2.cal 
      && -e $IMT_CONFIG/robots/planarhand/imt2.cal ]]; then
    eche
    eche "Click X on the browser window title bar to exit."
    eche
    eche tkdiff $IMT_CONFIG/robots/planar/imt2.cal $IMT_CONFIG/robots/planarhand/imt2.cal
    tkdiff $IMT_CONFIG/robots/planar/imt2.cal $IMT_CONFIG/robots/planarhand/imt2.cal
    # we need this sleep or firefox may get confused and not re-open
    # because it still sees the first one closing.
    sleep 1
    econt
fi

# else...
for i in $IMT_CONFIG/robots/*/imt2.cal
do
    
    # don't do this if it's a planar/hand pair
    if [[ $i == $IMT_CONFIG/robots/planarhand/imt2.cal 
         && -e $IMT_CONFIG/robots/planar/imt2.cal ]]; then
	continue
    fi
    if [[ $i == $IMT_CONFIG/robots/planar/imt2.cal 
         && -e $IMT_CONFIG/robots/planar/imt2.cal ]]; then
	continue
    fi

    firefox $i
    # we need this sleep or firefox may get confused and not re-open
    # because it still sees the first one closing.
    sleep 1
    econt
done

eche Cal file checks Done.
econt

eche Make sure there are no extra patient folders in $THERAPIST_HOME
eche "(except test or t)."
eche
eche ls -lL $THERAPIST_HOME
ls -lL $THERAPIST_HOME
econt

eche This is the date/time on this robot:
eche
date
eche
eche "Make sure it is correct and is set to the customer's time zone."
eche "If not, set it with the Gear Menu (top right) -> System Settings -> Date and Time"
eche "(do this by hand)."
econt

eche Check to see whether sendmachinereport has been run.
eche Check for machine_report files in /var/log/imt .
eche 
eche ls -ltr /var/log/imt
ls -ltr /var/log/imt
econt

if [[ $PERSONALITY == "ce" ]]; then
    eche "Check UEI board position and serial number."
    $CROB_HOME/go
    cat /proc/pwrdaq | grep 's/n\|board'
    $CROB_HOME/stop
    econt
fi

roblist=$(ls $IMT_CONFIG/robots)
eche Robot list: $roblist
for i in $roblist
do
    eche
    case $i in
	planar)
	    eche "Run Adaptive1 test"
	    echo planar > $IMT_CONFIG/current_robot
	    eche run planar zero
	    $CROB_HOME/tools/plcenter

	    $CROB_HOME/tools/${PERSONALITY}plc check-cal || continue

	    if [ -x $CROB_HOME/tools/ft_test ]; then
		eche run planar Force Transducer test
		$CROB_HOME/tools/ft_test
		econt
	    fi

	    eche run planar vex
	    $CROB_HOME/vex
	    eche run planar clock
	    PATID=test $LGAMES_HOME/clock/clock.tcl $PROTOCOLS_HOME/planar/clock/adaptive/therapy/adaptive_1 test
	    eche run planar maze
	    PATID=test $LGAMES_HOME/cs/runcs
	    ;;

	planarhand)
	    echo planarhand > $IMT_CONFIG/current_robot
	    eche run planarhand zero
	    $CROB_HOME/tools/plcenter

	    $CROB_HOME/tools/${PERSONALITY}plc -q check-cal || continue

	    eche run planarhand clock
	    PATID=test $LGAMES_HOME/clock/clock.tcl $PROTOCOLS_HOME/planarhand/clock/adaptivegrasp/therapy/grasp_pick_adaptive test
	    eche set robot type back to planar
	    echo planar > $IMT_CONFIG/current_robot
	    ;;

	wrist)
	    echo wrist > $IMT_CONFIG/current_robot
	    eche run wrist zero
	    $CROB_HOME/tools/wcenter

	    $CROB_HOME/tools/${PERSONALITY}plc -q check-cal || continue

	    eche run wrist clock
	    PATID=test $LGAMES_HOME/clock/clock.tcl $PROTOCOLS_HOME/wrist/clock/adaptive/therapy/wr_adaptive_2d_1 test
	    eche run wrist maze
	    PATID=test $LGAMES_HOME/cs/runcs
	    ;;

	*)
	    eche "No test for $i"
	    ;;

    esac
    eche "$i done"
    econt
done

eche check_prod script Done.
